### ISSUE TITLE
Refactor the `Avatar` component

### ISSUE THREAD

**Issue by lekowan** [lekowan/love-words#10]
# Description

The `Avatar` component currently relies on a lot of hardcoded variables, that can be refactored to be handled programmatically.

# Issues to resolve

There are some limitations to the implementation as it stands:

- [x] The `Avatar` component has a separate hardcoded element for each different avatar image. This should be simplified to simply render the correct image based on the `speaker` prop.
- [x] Consider whether there is a way to programmatically access each avatar image, rather than importing each individually. This should be possible by relocating the avatar image files as [static assets in the `/public` directory](https://nextjs.org/docs/app/building-your-application/optimizing/static-assets).

   At the very least, the import path for each image can be simplified by using [module aliases](https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases#module-aliases) rather than relative URLs e.g. change
   ```
   import Lama from "../../../assets/lama.png"
   ```
   to
   ```
   import Lama from "@/assets/lama.png"
   ```
- [ ] The format of the `speaker` field in the `[story-title].json` files does not match the image file names,  thus requiring transformation to kebab-case  This could be avoided if the `speaker` was consistently defined with kebab-case to begin with.
- [ ] Defining an exhaustive list of avatars in `AvatarProps.speaker` doesn't look very maintainable. It's not clear to me right now what a good alternative would be, other than just defaulting to `string` type.
- [x] Some stories contain speakers that aren't included in `AvatarProps.speaker` and do not have an associated image in `/public/avatars`, so the `GET` request for these images fail. See for example `shirokuma-cafe-episode-01-part1.json`, which includes speakers such as "PERSON" and "CLERK". This situation seems inevitable as the content increases, so having a nicer fallback for failing images is essential. For a guide on implementing a fallback for failing images see the [official _Vercel_ recomendation](https://vercel.com/templates/next.js/image-fallback) and [StackOverflow](https://stackoverflow.com/questions/66949606/what-is-the-best-way-to-have-a-fallback-image-in-nextjs).

**Comment by seanmturley** [comment]
The `Avatar` component now programmatically accesses the correct avatar image based on the `speaker` prop, with the images accessible at e.g. http://localhost:3000/avatars/panda.png.

There are some limitations to the implementation as it stands:
1. The `speaker` prop currently requires transformation to kebab-case to match files names. This could be avoided if the `speaker` in the story.json` files were consistently defined with kebab-case to begin with.
2. Defining an exhaustive list of avatars in `AvatarProps.speaker` doesn't look very maintainable. It's not clear to me right now what a good alternative would be, other than just defaulting to `string` type.
3. Some stories contain speakers that aren't included in `AvatarProps.speaker` and do not have an associated image in `/public/avatars`, so the `GET` request for these images fail. See for example `shirokuma-cafe-episode-01-part1.json` which includes speakers such as "PERSON" and "CLERK". This situation seems inevitable as the content increases, so having a nicer fallback for failing images is essential.

## To do
- [ ] Discuss points 1 and 2 above.
- [ ] Implement a fallback for failing images (see the [official _Vercel_ recomendation](https://vercel.com/templates/next.js/image-fallback) and [StackOverflow](https://stackoverflow.com/questions/66949606/what-is-the-best-way-to-have-a-fallback-image-in-nextjs).

**Comment by seanmturley** [comment]
I've added a simplistic form of error handling to the `Avatar` component that preserves the existing fallback to a `<div>` styled as a circle. We can add something more sophisticated later depending upon how we want to handle `speaker` and if we want to use an actual image as the fallback.

Things to consider for further refinement:
- The approach may be different if we want text to be displayed sometimes without an avatar.
- If an exhaustive list of `speaker` values is maintained, a fallback could be displayed if the provided value is not listed.
- If we want to use an actual image as the fallback, we can take [the approach suggested by _Vercel_](https://vercel.com/templates/next.js/image-fallback). This would allow the creation of a generalized `ImageWithFallback` component.

**Comment by seanmturley** [comment]
Removed `.toLowerCase()` from `speakerKebab` definition since URLs aren't case sensitive i.e. http://localhost:3000/avatars/panda.png is the same as http://localhost:3000/avatars/PANDA.png.

**Comment by seanmturley** [comment]
I'm going to merge this into main in it's current state as it's a decent improvement over the previous implementation.

There are some questions remaining:
- 2 unresolved issues in [the initial post](https://github.com/lekowan/love-words/issues/10#issue-2615369565)
- The points raised in [this post above](https://github.com/lekowan/love-words/issues/10#issuecomment-2439326131)

These can be discussed and addressed later when we have a clearer idea on how we want to proceed.

**Comment by seanmturley** [comment]
All images are failing on production. It seems the production domain may need to be specified in `images.remotePatterns` in `next.config`.

Also because the `[...slug]` page is in the root of the site, it's intercepting all requests and attempting to call `getStory()` on whatever URL `slug` it catches. Moving this dynamic route into a subdirectory should solve the issue (hopefully this isn't too complex).

**Comment by seanmturley** [comment]
A bit of testing on production revealed that the issue with images failing on production wasn't missing the `images.remotePatterns` from `next.config` (this is just for external resources), but rather the fact that [the _Vercel_ servers are _Unix_-based and thus treat URLs as case sensitive](https://stackoverflow.com/questions/77183534/nextjs-images-are-not-rendered-on-vercel)!

**Comment by seanmturley** [comment]
Noting there that the ideal way to implement the image fallback might be to use [fetch](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching) to check if the image exists, then render accordingly.

This could be done with something like the following pseudo code:
```
const imageExists = await fetch(`/avatars/${speakerKebab}.png`, {
  method: "HEAD",
})

if (imageExists) {
  // Render image
}
else {
  // Render fallback
}
```
This would allow `Avatar` to be a server component and fully benefit from server side caching.

This approach cannot currently be implemented since `StoryTemplate` (an ancestor ~3 levels above `Avatar`) is a client component. It may not be possible to rework `StoryTemplate` as a client component, though it would be good to try to [move the server/client boundary down the tree](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#moving-client-components-down-the-tree).
