### ISSUE TITLE
Refine dropdown menu path update

### ISSUE THREAD

**Issue by lekowan** [lekowan/love-words#31]
# Description

`Dropdown` is using `onClick`, `string.replace`, and a few hooks to navigate between routes. This can probably be simplified.

**Comment by seanmturley** [comment]
All the navigation between language routes is now achieved with `Link`, which makes the component a lot simpler.

There was an issue where the dropdown options wouldn't highlight correctly after the first time one is selected (the `data-highlighted` property was no longer added to the dropdown items). My guess is the `Link` was intercepting clicks on `DropdownUI.Item` and interfering with whatever magic _JavaScript_ is being applied by _Radix UI_ behind the scenes. This was solved by enabling the `asChild` prop on `DropdownUI.Item`, and then setting `display: block` on the `Link` to achieve the expected styling. It's possible there's a better way to do this.

**Comment by lekowan** [comment]
Awesome improvement! I don't think there is a better way of doing this: it's super clean!
